# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_script:
  - psql -c 'create database topjava' -U postgres
  - psql -c 'create user "user"; grant all privileges on database topjava to "user"' -U postgres

branches:
  only:
  - master
